### ISSUE TITLE
spikes don't care about breakable blocks

### ISSUE THREAD

**Issue by everett980** [Lancey6/girder-gus-maker#105]
spikes don't attack to breakable blocks the same way they attach to red or black bricks

**Comment by LanaCoyote** [comment]
Intended I think. Wouldn't be a hard fix but didn't make sense to me (and I assume Brian) from a usage perspective. If the block breaks, the spike will be left floating in mid-air. If Gus can't stand on the block because it's surrounded by spikes, why use a breakable one anyway?
