### ISSUE TITLE
Ghost Gus walks on (and destroys) Gus's break bricks if no ghost break bricks underneath

### ISSUE THREAD

**Issue by Yustynn** [Lancey6/girder-gus-maker#106]

**Comment by everett980** [comment]
temporary fix is to ensure that all real break bricks have a ghost break brick beneath? why wouldn't there be a ghost break brick for ALL regular break bricks?

**Comment by LanaCoyote** [comment]
If Gus walks over collapsing bricks and then makes his way back up to where they were and walked off the edge, he'll instead walk over the player's bricks and desync

**Comment by Yustynn** [comment]
Yup what David said. This'll be one of my first tomorrow problems.
