### ISSUE TITLE
It's possible to see outside of the grid

### ISSUE THREAD

**Issue by everett980** [Lancey6/girder-gus-maker#107]
if you rotate you see canvas without the grid applied. is it possible to to render the grid beyond the scope of the camera to maintain the illusion of a true grid?

**Comment by LanaCoyote** [comment]
Shouldn't be too hard, just need to increase `game.width/2` to `game.width*0.625` when drawing the grid the first time (3:4 resolution, therefore a=3, b=4, c=5, therefore c = 1.25b, therefore 0.5*1.25=0.625=b, note for me for later)
