### ISSUE TITLE
Ghost gus becomes increasingly out of sync as time progresses

### ISSUE THREAD

**Issue by Yustynn** [Lancey6/girder-gus-maker#122]
This is due to frame rate variations between different runs of the game.

Ghost gus replays each recorded frame from a particular game. He replays each frame in a new game, where the FPS is different. This changed FPS when he replays these frames results in his movement being different. 

Super annoying. I've got a suboptimal solution that might do. Will talk to you guys about it tomorrow morning.

**Comment by everett980** [comment]
closed
