### ISSUE TITLE
level deletion

### ISSUE THREAD

**Issue by everett980** [Lancey6/girder-gus-maker#126]
is this actually a feature we want? maybe make it admin only? i see no real need to let people redact their levels.

**Comment by Yustynn** [comment]
I think we want people to be able to delete their own levels. They're unlikely to delete good levels. Just bad ones, which we don't want anyway.

**Comment by LanaCoyote** [comment]
Seems like a good idea. Add a delete button and check on the backend that `req.user === level.creator || req.user.isAdmin`

**Comment by Yustynn** [comment]
Yeah. I already wrote a function in the crud helper called findByIdAndUpdateIfOwnerOrAdmin, or something suitably long-winded like that

**Comment by briancdunn** [comment]
I could add this to the profile page. The route already exists, so it's just a matter of adding a button.
