### ISSUE TITLE
Level Progress Never Implemented

### ISSUE THREAD

**Issue by everett980** [Lancey6/girder-gus-maker#143]
`browser/js/states/levels/levels.controller.js` should check if a level is published before pushing it to the all levels page

`browser/js/states/builder/builder.controller.js` should get all not published levels for a player and populate the page with level directives that would allow a user to continue developing a level they saved part way through

putting this as a git issue because i can't develop atm

**Comment by LanaCoyote** [comment]
The backend shouldn't even send unpublished levels to users that didn't publish them.
