### ISSUE TITLE
No indications of how to use anything

### ISSUE THREAD

**Issue by everett980** [Lancey6/girder-gus-maker#165]
it's **fairly** intuitive, but there are undeniably confusing moments (QWEASD camera control in level editor) and a simple right left space control explanation would be neat. like some kind of tutorial playlist that has game text telling the user how to control character. upon moving left, the hint for left goes away, upon moving right, the hint for right goes away, and upon placing a girder, the hint for girders goes away.

would be neat and truly beginner friendly with a simple tutorial.

**Comment by Yustynn** [comment]
@Lancey6 was pretty far along on this one yesterday evening (for the game at least).

**Comment by LanaCoyote** [comment]
Add level editor controls to the level editor page and we're good.

**Comment by Yustynn** [comment]
I'm closing this (because #171). Added a specific issue for the level editor controls.
