### ISSUE TITLE
Google OAuth only works on local host

### ISSUE THREAD

**Issue by everett980** [Lancey6/girder-gus-maker#166]
callback url doesn't work when someone else joins via 192.168.blah.blah:blah

**Comment by everett980** [comment]
will of course not be an issue once we deploy

**Comment by Yustynn** [comment]
Don't think this is high priority.

**Comment by Yustynn** [comment]
Thought I was the one who did the oauth, but I don't see it in my Google Dev Console. @everett980 might have been you.

I _think_ all that has to be done is changing the callback URL from localhost:1337 to 127.0.0.1:1337 in both the google dev console and development.js

**Comment by LanaCoyote** [comment]
127.0.0.1 is localhost, they refer to the same place. Someone connecting from a 192:: IP would be redirected by google back to their own machine (not our box), which breaks OAuth flow.

Unfortunately OAuth is a piece of shit for local testing because of this.
