### ISSUE TITLE
gus can get get lodged inside a block if he moves fast enough

### ISSUE THREAD

**Issue by everett980** [Lancey6/girder-gus-maker#216]
on let there be pizza if you drop from the tip of the pizza to the crust of the pizza, you'll end up two blocks deep.
![screen shot 2016-02-11 at 12 11 17 pm](https://cloud.githubusercontent.com/assets/3471184/12983946/9f3a3d90-d0b9-11e5-839a-12a3c5772c97.png)
also can be weird with single thick blocks for rotating, matt bryan was able to lodge into a break block and rotate 180 degrees before the block broke because he was inside.

**Comment by LanaCoyote** [comment]
Possibly a result of lag + the way physics works. Not possible for us to fix without changing engine or a major overhaul of how we load levels.
