### ISSUE TITLE
Level editor doesn't require any hammers (but game shows 1 hammer as default)

### ISSUE THREAD

**Issue by Yustynn** [Lancey6/girder-gus-maker#81]
![image](https://cloud.githubusercontent.com/assets/6380769/12804596/85228978-cac2-11e5-8c5d-cbbff5286786.png)

Yeah, we need to require at least 1 hammer.

**Comment by LanaCoyote** [comment]
Working as intended. It defaults to 1 hammer so that the game doesn't immediately end. We should require at least 1 tool before a level can be published, but not before it can be tested.

**Comment by everett980** [comment]
I like your proposed solution, I'll incorporate that into the "pre-save validation" that I can do in a controller / factory on the front end.
Once I implement the stretch goal of requiring a user to beat a level before the button to save is allowed, that would encapsulate the needs one or more hammer requirement.

**Comment by Yustynn** [comment]
Right, wasn't clear. The validation by level editor was what I meant

**Comment by Yustynn** [comment]
@everett980 Yeah that's nice. Can't beat your own hammerless level
