### ISSUE TITLE
Timer in Gus increments even when the game is not active

### ISSUE THREAD

**Issue by everett980** [Lancey6/girder-gus-maker#85]
For instance, if you die, click away before you have respawned, then come back. The timer will have increased.

**Comment by LanaCoyote** [comment]
Sort of intended. The timer is based on clock time rather than game time, so any time that passes while the game is paused counts as well.

**Comment by everett980** [comment]
it maxes out elegantly at 99:59 so it's not really a problem i suppose.

**Comment by everett980** [comment]
yustynn and i agree it should only count play time, not pause time (game.time - starting time of game)
