### ISSUE TITLE
Old callbacks do not unbind from eventEmitter

### ISSUE THREAD

**Issue by LanaCoyote** [Lancey6/girder-gus-maker#89]
This results in multiple callbacks being called for each event emitted.

**Comment by LanaCoyote** [comment]
We're unbinding some of them, but I'm not happy about how we're doing it. I'd rather add a method that could replace all the handlers on an event automatically.

**Comment by LanaCoyote** [comment]
fixed in #128

**Comment by everett980** [comment]
fixed in #128
